name: InkWisps Instagram Post

on:
  schedule:
    - cron: '0 19 * * *'
    - cron: '24 21 * * *'
    - cron: '48 23 * * *'
    - cron: '12 2 * * *'
    - cron: '36 4 * * *'
    - cron: '0 7 * * *'
    - cron: '24 9 * * *'
    - cron: '48 11 * * *'
    - cron: '12 14 * * *'
    - cron: '36 16 * * *'
  workflow_dispatch:

jobs:
  post_to_instagram:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      IG_INKWISPS_TOKEN: ${{ secrets.IG_INKWISPS_TOKEN }}
      IG_INKWISPS_ID: ${{ secrets.IG_INKWISPS_ID }}
      DROPBOX_INKWISPS_APP_KEY: ${{ secrets.DROPBOX_INKWISPS_APP_KEY }}
      DROPBOX_INKWISPS_APP_SECRET: ${{ secrets.DROPBOX_INKWISPS_APP_SECRET }}
      DROPBOX_INKWISPS_REFRESH: ${{ secrets.DROPBOX_INKWISPS_REFRESH }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 🔧 Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: 📦 Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dropbox requests python-telegram-bot==13.15 pytz pynacl
          pip install imageio imageio-ffmpeg
          pip install moviepy==1.0.3

      - name: 🧪 Verify moviepy Installation
        run: python -c "from moviepy.editor import VideoFileClip; print('✅ moviepy 1.0.3 loaded')"

      - name: 🚀 Run Instagram Uploader
        run: python inkwisps_post.py
