name: InkWisps Instagram Post

on:
  schedule:
    - cron: '0 3 * * *'     # 03:00 UTC
    - cron: '0 10 * * *'    # 10:00 UTC
    - cron: '0 12 * * *'    # 12:00 UTC
    - cron: '0 15 * * *'    # 15:00 UTC
    - cron: '0 17 * * *'    # 17:00 UTC
    - cron: '0 22 * * *'    # 22:00 UTC
  workflow_dispatch:        # allows manual trigger via GitHub UI

jobs:
  post_to_instagram:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      IG_INKWISPS_TOKEN: ${{ secrets.IG_INKWISPS_TOKEN }}
      IG_INKWISPS_ID: ${{ secrets.IG_INKWISPS_ID }}
      DROPBOX_INKWISPS_APP_KEY: ${{ secrets.DROPBOX_INKWISPS_APP_KEY }}
      DROPBOX_INKWISPS_APP_SECRET: ${{ secrets.DROPBOX_INKWISPS_APP_SECRET }}
      DROPBOX_INKWISPS_REFRESH: ${{ secrets.DROPBOX_INKWISPS_REFRESH }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install Dependencies
        run: |
          pip install --upgrade pip
          pip install dropbox requests python-telegram-bot==13.15 pytz pynacl

      - name: 🚀 Run Instagram Uploader
        run: python inkwisps_post.py
